# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: core
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: prod
  region: eu-west-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
      Resource: "*"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  individually: true
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  findMenuList:
    handler: handler.findMenuList
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: menuList/{active}
          method: get
          cors: true
          request:
            parameters:
              paths:
                active: true
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:eu-west-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
    environment:
      COLLECTION_NAME: "menu"

  findPromotionList:
    handler: handler.findPromotionList
    events:
      - http:
          path: promotionList/{active}
          method: get
          cors: true
          request:
            parameters:
              paths:
                active: true
    environment:
      COLLECTION_NAME: "promotion"

  findAboutUsList:
    handler: handler.findAboutUsList
    events:
      - http:
          path: aboutUsList
          method: get
          cors: true
    environment:
      COLLECTION_NAME: "aboutUs"

  findTermsAndConditionsList:
    handler: handler.findTermsAndConditionsList
    events:
      - http:
          path: termsAndConditionsList
          method: get
          cors: true
    environment:
      COLLECTION_NAME: "termsAndConditions"

  findPrivacyPolicyList:
    handler: handler.findPrivacyPolicyList
    events:
      - http:
          path: privacyPolicyList
          method: get
          cors: true
    environment:
      COLLECTION_NAME: "privacyPolicy"

  findFrequentlyAskedQuestionList:
    handler: handler.findFrequentlyAskedQuestionList
    events:
      - http:
          path: frequentlyAskedQuestionList
          method: get
          cors: true
    environment:
      COLLECTION_NAME: "frequentlyAskedQuestion"

  findCountryByCode:
    handler: handler.findCountryByCode
    events:
      - http:
          path: countryByCode/{countryCode}
          method: get
          cors: true
          request:
            parameters:
              paths:
                countryCode: true
    environment:
      COLLECTION_NAME: "country"

  findCountryByName:
    handler: handler.findCountryByName
    events:
      - http:
          path: countryByName/{countryName}
          method: get
          cors: true
          request:
            parameters:
              paths:
                countryName: true
    environment:
      COLLECTION_NAME: "country"

  createAuditEntry:
    handler: handler.createAuditEntry
    events:
      - http:
          path: auditEntry
          method: post
          cors: true
    environment:
      COLLECTION_NAME: "audit"

# you can add CloudFormation resource templates here
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    include:
      - DB_NAME
      - REGION
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.taleofddh.com
    staging: staging-api.taleofddh.com
    dev: dev-api.taleofddh.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: "core"
    stage: ${self:custom.stage}
    certificateName: "*.taleofddh.com"
    hostedZoneId: ${opt:HOSTED_ZONE_ID}
    createRoute53Record: true
    endpointType: edge
    securityPolicy: tls_1_2
    apiType: rest
