# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: blog
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: prod
  region: eu-west-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  individually: true

functions:
  findBlogList:
    handler: handler.findBlogList
    events:
      - http:
          path: blogList
          method: get
          cors: true
    environment:
      COLLECTION_NAME: "blog"

  findCategorizedBlogList:
    handler: handler.findCategorizedBlogList
    events:
      - http:
          path: blogListCategorized
          method: post
          cors: true
    environment:
      COLLECTION_NAME: "blog"

  findBlogArticleList:
    handler: handler.findBlogArticleList
    events:
      - http:
          path: blogArticleList
          method: post
          cors: true
    environment:
      COLLECTION_NAME: "article"

  findArticleList:
    handler: handler.findArticleList
    events:
      - http:
          path: articleList
          method: post
          cors: true
    environment:
      COLLECTION_NAME: "article"

  findArticleCommentList:
    handler: handler.findArticleCommentList
    events:
      - http:
          path: articleCommentList
          method: post
          cors: true
    environment:
      COLLECTION_NAME: "articleComment"

  addArticleComment:
    handler: handler.addArticleComment
    events:
      - http:
          path: articleComment
          method: post
          cors: true
    environment:
      COLLECTION_NAME: "articleComment"

# you can add CloudFormation resource templates here
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    include:
      - DB_NAME
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.taleofddh.com
    staging: staging-api.taleofddh.com
    dev: dev-api.taleofddh.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: "blog"
    stage: ${self:custom.stage}
    certificateName: "*.taleofddh.com"
    hostedZoneId: ${opt:HOSTED_ZONE_ID}
    createRoute53Record: true
    endpointType: edge
    securityPolicy: tls_1_2
    apiType: rest
